config/routes.rb
Rails.application.routes.draw do
  resources :categories

  get 'category/new'

  resources :contrats

  resources :offres
  devise_for :users, :controllers => {:registrations => "users/registrations"}

  devise_scope :user do
    authenticated :user do
      root :to => 'offres#index', as: :authenticated_root
    end
    unauthenticated :user do
      root :to => 'devise/sessions#new', as: :unauthenticated_root
    end
  end

end

app/models/contrat.rb
class Contrat < ActiveRecord::Base

end

app/controllers/contrats_controller.rb
class ContratsController < ApplicationController
  before_action :set_contrat, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  respond_to :html

  def index
    @contrats = Contrat.all
    respond_with(@contrats)
  end

  def show
    respond_with(@contrat)
  end

  def new
    @contrat = Contrat.new
    respond_with(@contrat)
  end

  def edit
  end

  def create
    @contrat = Contrat.new(contrat_params)
    @contrat.save
    respond_with(@contrat)
  end

  def update
    @contrat.update(contrat_params)
    respond_with(@contrat)
  end

  def destroy
    @contrat.destroy
    respond_with(@contrat)
  end

  private
    def set_contrat
      @contrat = Contrat.find(params[:id])
    end

    def contrat_params
      params.require(:contrat).permit(:startDate, :endDate, :offre_id, :offreur_id, :demandeur_id)
    end
end

app/helpers/contrats_helper.rb
module ContratsHelper
end

app/views/contrats/_form.html.erb
<%= form_for(@contrat) do |f| %>
  <% if @contrat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contrat.errors.count, "error") %> prohibited this contrat from being saved:</h2>

      <ul>
      <% @contrat.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :startDate %><br>
    <%= f.datetime_select :startDate %>
  </div>
  <div class="field">
    <%= f.label :endDate %><br>
    <%= f.datetime_select :endDate %>
  </div>
  <div class="field">
    <%= f.label :offre_id %><br>
    <%= f.number_field :offre_id %>
  </div>
  <div class="field">
    <%= f.label :offreur_id %><br>
    <%= f.number_field :offreur_id %>
  </div>
  <div class="field">
    <%= f.label :demandeur_id %><br>
    <%= f.number_field :demandeur_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contrats/edit.html.erb
<h1>Editing contrat</h1>

<%= render 'form' %>

<%= link_to 'Show', @contrat %> |
<%= link_to 'Back', contrats_path %>

app/views/contrats/index.html.erb
<h1>Listing contrats</h1>

<table>
  <thead>
    <tr>
      <th>Startdate</th>
      <th>Enddate</th>
      <th>Offre</th>
      <th>Offreur</th>
      <th>Demandeur</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contrats.each do |contrat| %>
      <tr>
        <td><%= contrat.startDate %></td>
        <td><%= contrat.endDate %></td>
        <td><%= contrat.offre_id %></td>
        <td><%= contrat.offreur_id %></td>
        <td><%= contrat.demandeur_id %></td>
        <td><%= link_to 'Show', contrat %></td>
        <td><%= link_to 'Edit', edit_contrat_path(contrat) %></td>
        <td><%= link_to 'Destroy', contrat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contrat', new_contrat_path %>

app/views/contrats/new.html.erb
<h1>New contrat</h1>

<%= render 'form' %>

<%= link_to 'Back', contrats_path %>

app/views/contrats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Startdate:</strong>
  <%= @contrat.startDate %>
</p>

<p>
  <strong>Enddate:</strong>
  <%= @contrat.endDate %>
</p>

<p>
  <strong>Offre:</strong>
  <%= @contrat.offre_id %>
</p>

<p>
  <strong>Offreur:</strong>
  <%= @contrat.offreur_id %>
</p>

<p>
  <strong>Demandeur:</strong>
  <%= @contrat.demandeur_id %>
</p>

<%= link_to 'Edit', edit_contrat_path(@contrat) %> |
<%= link_to 'Back', contrats_path %>