config/routes.rb
Rails.application.routes.draw do
  resources :categories

  get 'category/new'

  resources :contrats

  resources :offres
  devise_for :users, :controllers => {:registrations => "users/registrations"}

  devise_scope :user do
    authenticated :user do
      root :to => 'offres#index', as: :authenticated_root
    end
    unauthenticated :user do
      root :to => 'devise/sessions#new', as: :unauthenticated_root
    end
  end

end

app/models/offre.rb
class Offre < ActiveRecord::Base
  belongs_to :user
  belongs_to :category

  validates :user_id, :presence => true

  #Geocode
  geocoded_by :address
  after_validation :geocode, :if => :address_changed?

  # get address from user
  def address
    user.address
  end

  def address_changed?
    user.address_changed?
  end

  def longitude
    user.longitude
  end

  def latitude
    user.latitude
  end


  # validates image
  # has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" },  :default_url => "/images/:style/missing.png"
  #validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  #validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  validates_attachment_content_type :image, :content_type => /\Aimage/

  # validates category
  validates :category, presence: true

  # search
  def self.search(search)
    if search
      where('title LIKE ? OR descr LIKE ?', "%#{search}%", "%#{search}%")
    else
      all
    end
  end
end

app/controllers/offres_controller.rb
require 'border_patrol'

class OffresController < ApplicationController
  before_action :set_offre, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, :prepare_categories
  respond_to :html

  def index
    ratio = 4
    if(params[:search].present?)
      @offres = Offre.search(params[:search])
      if(@offres.empty?)
        respond_to do |format|
          format.html{redirect_to offres_path, notice: 'Pas de résultats' }
        end
      end
    else
      @offres = Offre.all
    end

    @hash = Gmaps4rails.build_markers(@offres) do |offre, marker|
      marker.lat offre.latitude
      marker.lng offre.longitude
      marker.picture({
                       # "url" => "https://addons.cdn.mozilla.net/img/uploads/addon_icons/13/13028-64.png",
                       "width" =>  36,
                       "height" => 36})
      marker.infowindow render_to_string(:partial => "/offres/offre", :locals => {:offre => offre})
      marker.json({:descr => offre.descr,strokeWeight: 6.0})

    end
    #respond_with(@offres, @hash)
  end

  def show
    respond_with(@offre)
  end

  def new
    @offre = current_user.offres.new
    respond_with(@offre)
  end

  def edit
  end

  def create
    @offre = current_user.offres.new(offre_params)
    @offre.save
    respond_with(@offre)
  end

  def update
    @offre.update(offre_params)
    respond_with(@offre)
  end

  def destroy
    @offre.destroy
    respond_with(@offre)
  end

  def mine
    @offres = current_user.offres
    respond_with(@offres)
  end

  private
  def set_offre
    @offre = Offre.find(params[:id])
  end

  def prepare_categories
    @categories = Category.all
  end

  def offre_params
    params.require(:offre).permit(:title, :descr, :price, :image, :category, :longitude, :latitude, :address, :category_id)
  end
end

app/helpers/offres_helper.rb
module OffresHelper
end

app/views/offres/_form.html.erb
<%= form_for(@offre, :url => offres_path, :html => {:multipart => true}) do |f| %>
    <div class="row">
      <div class="col-md-4">
        <% if @offre.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@offre.errors.count, "error") %> prohibited this offre from being saved:</h2>
              <ul>
                <% @offre.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
              </ul>
            </div>
        <% end %>

        <div class="field">
          <%= f.label :title %>
          <br>
          <%= f.text_field :title %>
        </div>
        <div class="field">
          <%= f.label :descr %>
          <br>
          <%= f.text_area :descr %>
        </div>
        <div class="field">
          <%= f.label :price %>
          <br>
          <%= f.number_field :price %>
        </div>

        <div class="field">
          <%= f.label :categorie %>
          <br>
          <%= f.collection_select(:category_id, @categories, :id, :name, :include_blank => "Please select") %>
        </div>



      </div>
      <div class="col-md-4">
        <input type="file" class="btn btn-info2 btn-file" id='offre_image' name='offre[image]' />
        <br/>
        <img id="image_offre" src="../assets/perso/empty_tool.png" alt="Offer image" width="200px"/>
      </div>
      <div class="row">
        <div class="col-md-8">
          <div class="actions">
            <%= f.submit class:'btn btn-success' %>
          </div>
        </div>
      </div>
    </div>
<% end %>

<script>
    function readURL(input) {

        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $('#image_offre').attr('src', e.target.result);
            }

            reader.readAsDataURL(input.files[0]);
        }
    }

    $("#offre_image").change(function(){
        readURL(this);
    });
</script>

app/views/offres/_offre.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= offre.title %>
</p>

<p>
  <strong>Descr:</strong>
  <%= offre.descr %>
</p>

<p>
  <strong>Price:</strong>
  <%= offre.price %>
</p>

app/views/offres/_offre_home.erb
<tr onclick=''>
  <td>
    <% if offre.image? %>
        <%= image_tag(offre.image.url, height: 50) %>
    <% else %>
        <%= image_tag('perso/empty_tool.png', height: 50) %>
    <% end %>
  </td>
  <td>
    <b><%= offre.title %></b><br/> <%= offre.descr %>
  </td>
  <td>
    <%- if offre.price == 0 %> Gratuit
        <% else %><%= offre.price %> CHF
    <% end -%></td>
  <td>
    <%= offre.category.name %>
  </td>
  <td align="right">
    <% if offre.user_id == current_user.id %>
        <%= link_to 'Modifier mon offre', offre, :class => 'btn btn-info' %>
    <% else %>
        <%= link_to 'Consulter', offre, :class => 'btn btn-success' %>
    <% end %>
  </td>
</tr>

app/views/offres/edit.html.erb
<h1>Editing offre</h1>

<%= render 'form' %>

<%= link_to 'Show', @offre %> |
<%= link_to 'Back', offres_path %>

app/views/offres/index.html.erb
<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
<div class="row">
  <div class="col-md-1">&NonBreakingSpace;</div>
  <div class="col-md-6">
    <h3>Les offres près de chez moi !</h3>
    <div class='search-offre'>
      <%= form_tag offres_path, :method => 'get' ,:id => 'offres_search' do %>
            <%= text_field_tag :search, params[:search] %>
            <%= submit_tag "Search", :name => nil, :class => 'btn btn-primary' %>
      <% end %>
    </div>
    <br/>
    <table class='offer-container table'>
      <% if flash[:notice] %>
          <p id="notice"><%= flash[:notice] %></p>
      <% end %>
      <tbody class='offre-home'>
      <% if !@offres.empty? %>
          <% @offres.each do |offre| %>
              <%= render 'offres/offre_home', :offre => offre %>
          <% end %>
      <% end %>
      </tbody>
    </table>
  </div>
  <div class="col-md-4">
    <div class="space-30"></div>
      <div class="col-md-offset-1">
        <div id="with_kml" ></div>
      </div>
    </div>
  </div>
</div>

<script>
  $(function(){
    var handler = Gmaps.build('Google');
    handler.buildMap({ provider: {}, internal: {id: 'with_kml'}}, function(){
      var kmls = handler.addKml(
              { url: "https://www.dropbox.com/s/vstzf5g79qcp2qn/GEO_GIREC.kmz?raw=1"
              }
      );
      markers = handler.addMarkers(<%= raw @hash.to_json %>);
      handler.bounds.extendWith(markers);
      handler.fitMapToBounds();
      handler.getMap().setZoom(8);
        var polygon_options = {
            paths: poly,
            strokeColor: color,
            strokeOpacity: 0.7,
            strokeWeight: 2,
            fillColor: "ff0000",
            fillOpacity: 0.2
        };
        handler.setOptions({strokeWeight: 6.0});
        marker.setOptions({strokeWeight: 6.0});
      handler.callback();
    });
  });
</script>

app/views/offres/new.html.erb
<div class="row">
  <div class="col-md-2"></div>
  <div class="col-md-8">
    <div class="row">
        <h1>Nouvelle offre</h1>
    </div>
    <%= render 'form' %>
    <%= link_to 'Back', offres_path %>
  </div>
  <div class="col-md-2"></div>
</div>

app/views/offres/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @offre.title %>
</p>

<p>
  <strong>Descr:</strong>
  <%= @offre.descr %>
</p>

<p>
  <strong>Price:</strong>
  <%= @offre.price %>
</p>

<%= link_to 'Edit', edit_offre_path(@offre) %> |
<%= link_to 'Back', offres_path %>